### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by TheKrafter** [h22679/ccbt-modpack-checker#1]
This is EPIC btw, and I know of a project that would love to use it.

Could you publish some docs that explain the architecture of the system, and how to set up the backend of it?

Ty <3

**Comment by h22679** [comment]
Thank you!

I added a basic explanation of the mod, I'll work on more detailed explanations of how it works internally and the API it communicates with 👍

**Comment by h22679** [comment]
Added a wiki with more info, feel free to request more details if needed.
